name: Health Check

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  health-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Start application
        run: |
          npm start &
          sleep 10

      - name: Run health checks
        run: |
          echo "🔍 Running health checks..."

          # Wait for server to be ready
          for i in {1..30}; do
            if curl -s -f http://localhost:3000 > /dev/null 2>&1; then
              echo "✅ Server is ready"
              break
            fi
            echo "⏳ Waiting for server... ($i/30)"
            sleep 2
          done

          # Run health check
          HEALTH_RESPONSE=$(curl -s http://localhost:3000/api/health-check-public)
          HEALTH_STATUS=$(echo "$HEALTH_RESPONSE" | jq -r '.overall // "unknown"')

          if [ "$HEALTH_STATUS" = "unhealthy" ]; then
            echo "❌ Health checks failed!"
            echo "Failed checks:"
            echo "$HEALTH_RESPONSE" | jq -r '.checks[] | select(.status == "fail") | "- " + .name + ": " + .message'
            exit 1
          fi

          echo "✅ All health checks passed!"

      - name: Test production invite flow
        run: |
          echo "🧪 Testing production invite flow..."
          npx tsx test-invite-flow.ts
